version: "3.8"
services:
  ## db services
  db:

   image: mongo: 6.0
   environment:
   MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
   MONGO_INITDB_ROOT_DATABASE: ${MONGO_INITDB_ROOT_DATABASE}
  volumes:
   - db_data:/data/db
  ports:
   - "27017:27017"


  ## Backend services
  backend:
  build:
    context: ./backend
    dockerfile: Dockerfile
  ports:
    - "${BACKEND_PORT}"
  environment:
  NODE_ENV: ${NODE_ENV}
  MONGO_URI: ${MONGO_URI}
  volumes:
   - ./backend:/app
  depends_on:
   - db
  
  ## Frontend service
  frontend:
  build:
    context: ./frontend
    dockerfile: Dockerfile
  ports:
    - "${FRONTEND_PORT}"
  environment:
  NODE_ENV: development
  volumes:
   - ./frontend:/app
  depends_on:
   - backend

volumes:
  db_data:

